version: '3'

services:
  postgres:
    image: postgres:15.0
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - word-learner
  backend:
    image: 833725/word-learner:backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - word-learner
  frontend:
    image: 833725/word-learner:frontend
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - word-learner
networks:
  word-learner:
    driver: bridge