spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    url: jdbc:postgresql://${PG_HOST}/${DB_NAME}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#logging:
#  level:
#    root: debug
jwt:
  token:
    secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855